require_relative '../node_modules/react-native-permissions/scripts/setup'

# Add react-native-permissions handlers
setup_permissions([
  'Camera',
  'Contacts',
  'LocationWhenInUse',
  'PhotoLibrary',
  'Microphone',
])

require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'FlashDrop' do
  config = use_native_modules!

  # EXPLICITLY DISABLE NEW ARCHITECTURE HERE
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true,
    :fabric_enabled => false,
    :new_arch_enabled => false
  )

  target 'FlashDropTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
